# -*- coding: utf-8 -*-
"""Mod-yolov8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dFtZ_jLnlUUsQ1IMCK095ozAM4LN7RAv
"""

from google.colab import drive
drive.mount('/content/drive')

import os
os.environ['CUDA_VISIBLE_DEVICES'] = "0"

!pip install --upgrade ultralytics

# !pip install ultralytics
!pip3 install --upgrade ultralytics
# !pip install --force-reinstall ultralytics

!pip install --upgrade torch
!pip install --upgrade ultralytics

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/drive/MyDrive/ComputerVisionBat/ultralytics # Required when using custom model architecture or else it will try to use default public one

!pip install -e .

from ultralytics import YOLO

model = YOLO('/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/models/v8/YOLOv8m-p2p.yaml')

# Train the model
train_results = model.train(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    epochs=100,
    batch=1, patience = 25
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPconv"
)

"""Evaluation on Validation Set"""

from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPconv/train/weights/best.pt")
metrics = model.val(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    batch=1,
    conf=0.2,
    # iou=0.3,
    show_labels=False,
    show_conf=False,
    # save_json=True,
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPconv/detect/val_30"
)
print(metrics)



"""Result from Validation after using Pconv on yolov8n:
* Precision: 0.7273
* Recall: 0.5183
* mAP@0.5: 0.6377
* mAP@0.5:0.95: 0.3232

* Precision: About 72.7% of detected boxes are correct (low false positives).
Recall: Model found about 51.8% of all true objects (misses some).

Result using Yolov8n
* Precision: 0.6307
* Recall: 0.4618
* mAP@0.5: 0.4881
* mAP@0.5:0.95: 0.2067

Test Set
* Precision: 0.6046
* Recall: 0.4932
* mAP@0.5: 0.4940
* mAP@0.5:0.95: 0.2118

Evaluation on Test Set
"""

from ultralytics import YOLO
from re import split
# Load your trained model (best.pt from training)
model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs/detect/train/weights/best.pt")

# Run evaluation on the test set
metrics_test = model.val(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    split = "test",
    batch=1,
    show_labels=False,
    show_conf=False
)

"""**Prediction**"""

from ultralytics import YOLO
from re import split
# Load your trained model (best.pt from training)
model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs/detect/train/weights/best.pt")

result = model.predict(source="/content/drive/MyDrive/ComputerVisionBat/BatDetection.yolov8/test/images",
    conf=0.25,
    batch=1,
    show_labels=False,
    show_conf=False,
    save=True,
    save_txt=True

)

from IPython.display import Image, display

display(Image("/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs/detect/val/confusion_matrix.png"))

mp, mr, map50, map = metrics.mean_results()

print(f"Precision: {mp:.4f}")
print(f"Recall: {mr:.4f}")
print(f"mAP@0.5: {map50:.4f}")
print(f"mAP@0.5:0.95: {map:.4f}")

display(Image("/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs/detect/test/confusion_matrix.png"))
mp, mr, map50, map = metrics_test.mean_results()
print(f"Precision: {mp:.4f}")
print(f"Recall: {mr:.4f}")
print(f"mAP@0.5: {map50:.4f}")
print(f"mAP@0.5:0.95: {map:.4f}")
print("AP75:", metrics.box.map75)

"""YOLOV8n PConv"""

import os
from PIL import Image, ImageDraw
from IPython.display import display

# Paths
results_dir = "/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs/detect/predict"
ground_truth_dir = "/content/drive/MyDrive/ComputerVisionBat/BatDetection.yolov8/test/labels"

# List images
image_files = [f for f in os.listdir(results_dir) if f.endswith((".jpg", ".png"))]

for img_file in image_files[:10]:
    img_path = os.path.join(results_dir, img_file)
    img = Image.open(img_path)
    draw = ImageDraw.Draw(img)

    # Draw ground truth boxes
    label_file = os.path.join(ground_truth_dir, os.path.splitext(img_file)[0] + ".txt")
    if os.path.exists(label_file):
        with open(label_file, "r") as f:
            for line in f.readlines():
                class_id, x_center, y_center, width, height = map(float, line.strip().split())
                img_w, img_h = img.size
                x_center *= img_w
                y_center *= img_h
                width *= img_w
                height *= img_h
                x0 = x_center - width / 2
                y0 = y_center - height / 2
                x1 = x_center + width / 2
                y1 = y_center + height / 2
                draw.rectangle([x0, y0, x1, y1], outline="red", width=2)  # Ground truth = red

    # draw YOLO predicted boxes (if predictions are saved in .txt)
    pred_txt_file = os.path.join(results_dir, "labels", os.path.splitext(img_file)[0] + ".txt")
    if os.path.exists(pred_txt_file):
        with open(pred_txt_file, "r") as f:
            for line in f.readlines():
                class_id, x_center, y_center, width, height, conf = map(float, line.strip().split())
                img_w, img_h = img.size
                x_center *= img_w
                y_center *= img_h
                width *= img_w
                height *= img_h
                x0 = x_center - width / 2
                y0 = y_center - height / 2
                x1 = x_center + width / 2
                y1 = y_center + height / 2
                draw.rectangle([x0, y0, x1, y1], outline="green", width=2)

    display(img)



import pandas as pd
import matplotlib.pyplot as plt

# Load the results file
results_path = "/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs/detect/train/results.csv"
df = pd.read_csv(results_path)

# Plot training loss curves
plt.figure(figsize=(12, 6))
plt.plot(df['epoch'], df['train/box_loss'], label='Box Loss')
plt.plot(df['epoch'], df['train/cls_loss'], label='Class Loss')
plt.plot(df['epoch'], df['train/dfl_loss'], label='DFL Loss')
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Training Loss Curves")
plt.legend()
plt.grid(True)
plt.show()

# Plot mAP
plt.figure(figsize=(12, 6))
plt.plot(df['epoch'], df['metrics/mAP50(B)'], label='mAP@0.5')
plt.plot(df['epoch'], df['metrics/mAP50-95(B)'], label='mAP@0.5:0.95')
plt.xlabel("Epoch")
plt.ylabel("mAP")
plt.title("Validation mAP over Epochs")
plt.legend()
plt.grid(True)
plt.show()

# Compute total losses
df["train_total_loss"] = df["train/box_loss"] + df["train/cls_loss"] + df["train/dfl_loss"]
df["val_total_loss"] = df["val/box_loss"] + df["val/cls_loss"] + df["val/dfl_loss"]

# Plot
plt.figure(figsize=(10, 6))
plt.plot(df["epoch"], df["train_total_loss"], label="Training Loss")
plt.plot(df["epoch"], df["val_total_loss"], label="Validation Loss")
plt.xlabel("Epoch")
plt.ylabel("Total Loss")
plt.title("Training vs Validation Loss")
plt.legend()
plt.grid(True)
plt.show()

import numpy as np
# Find the index of the minimum y-value
min_y_index_train = np.argmin(df["train_total_loss"])
min_y_index_val = np.argmin(df["val_total_loss"])

print(min_y_index_train)





"""Trying **Yolov8m**"""

pip install -U ultralytics

from ultralytics import YOLO

model = YOLO('/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/models/v8/yolov8m-p2p.yaml')

# Train the model
train_results = model.train(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    epochs=100,
    batch=1, patience = 20,
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPconv"
)

"""Evaluation on Validation Set"""

from ultralytics import YOLO

# Load your trained model (best.pt from training)
model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPconv/train2/weights/best.pt")

# Run evaluation on the validation set
metrics = model.val(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    batch=1,
    show_labels=False,
    show_conf=False
)

import shutil

# Define source and destination paths
src_path = "/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs/detect/val"
dst_path = "/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPconv"

# Move the file (no copy is made)
shutil.move(src_path, dst_path)

"""**Prediction**"""

from ultralytics import YOLO

# Load your trained model (best.pt from training)
model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralyticsWorking/runs_mPconv/train/weights/best.pt")

result = model.predict(source="/content/drive/MyDrive/ComputerVisionBat/BatDetection.yolov8/test/images",
    conf=0.2,
    batch=1,
    show_labels=False,
    show_conf=False,
    save=True,
    save_txt = True,
    project = "/content/drive/MyDrive/ComputerVisionBat/ultralyticsWorking/runs_mPconv/predict"

)

from IPython.display import Image, display

display(Image("/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPconv/val/confusion_matrix.png"))

mp, mr, map50, map = metrics.mean_results()

print(f"Precision: {mp:.4f}")
print(f"Recall: {mr:.4f}")
print(f"mAP@0.5: {map50:.4f}")
print(f"mAP@0.5:0.95: {map:.4f}")

import os
from PIL import Image, ImageDraw
from IPython.display import display

# Paths
results_dir = "/content/drive/MyDrive/ComputerVisionBat/ultralyticsWorking/runs_mPconv/predict/predict"
ground_truth_dir = "/content/drive/MyDrive/ComputerVisionBat/BatDetection.yolov8/test/labels"

# List images
image_files = [f for f in os.listdir(results_dir) if f.endswith((".jpg", ".png"))]

for img_file in image_files[:10]:
    img_path = os.path.join(results_dir, img_file)
    img = Image.open(img_path)
    draw = ImageDraw.Draw(img)

    # Ground truth boxes
    label_file = os.path.join(ground_truth_dir, os.path.splitext(img_file)[0] + ".txt")
    if os.path.exists(label_file):
        with open(label_file, "r") as f:
            for line in f.readlines():
                class_id, x_center, y_center, width, height = map(float, line.strip().split())
                img_w, img_h = img.size
                x0 = (x_center - width / 2) * img_w
                y0 = (y_center - height / 2) * img_h
                x1 = (x_center + width / 2) * img_w
                y1 = (y_center + height / 2) * img_h
                draw.rectangle([x0, y0, x1, y1], outline="red", width=2)

    # Predicted boxes
    pred_txt_file = os.path.join(results_dir, os.path.splitext(img_file)[0] + ".txt")
    if os.path.exists(pred_txt_file):
        with open(pred_txt_file, "r") as f:
            for line in f.readlines():
                parts = list(map(float, line.strip().split()))
                if len(parts) == 5:
                    class_id, x_center, y_center, width, height = parts
                elif len(parts) == 6:
                    class_id, x_center, y_center, width, height, conf = parts
                else:
                    continue

                img_w, img_h = img.size
                x0 = (x_center - width / 2) * img_w
                y0 = (y_center - height / 2) * img_h
                x1 = (x_center + width / 2) * img_w
                y1 = (y_center + height / 2) * img_h
                draw.rectangle([x0, y0, x1, y1], outline="green", width=2)

    display(img)  # works in notebook

"""Metrics after using yolov8m with Pconv
* Precision: 0.7974
* Recall: 0.5957
* mAP@0.5: 0.6570
* mAP@0.5:0.95: 0.3176

Result from Validation using yolov8n with Pconv
* Precision: 0.7273
* Recall: 0.5183
* mAP@0.5: 0.6377
* mAP@0.5:0.95: 0.3232


Result using Yolov8n
* Precision: 0.6307
* Recall: 0.4618
* mAP@0.5: 0.4881
* mAP@0.5:0.95: 0.2067

# runs_mPconvBi
"""

from ultralytics import YOLO

model = YOLO('/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/models/v8/yolov8m-p2p.yaml')

# Train the model
train_results = model.train(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    epochs=100,
    batch=1, patience = 20,
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPconvBi"
)

from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPconvBi/train/weights/last.pt")

model.train(resume=True)

from ultralytics import YOLO

# Load your trained model (best.pt from training)
model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPconvBi/train/weights/best.pt")

# Run evaluation on the validation set
val_metrics = model.val(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    batch=1,
    show_labels=False,
    show_conf=False,
    save_json=True,         # saves results in COCO-style JSON (detections)
    save_txt=True,          # saves detection boxes in YOLO txt format
    save=True,
    project = "/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPconvBi/detect"
)

from ultralytics import YOLO

# Load your trained model (best.pt from training)
model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPconvBi/train/weights/best.pt")


result = model.predict(source="/content/drive/MyDrive/ComputerVisionBat/BatDetection.yolov8/test/images",
    conf=0.2,
    batch=1,
    show_labels=False,
    show_conf=False,
    save=True,
    project = "/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPconvBi/detect",
    save_txt = True

)

import os
from PIL import Image, ImageDraw
from IPython.display import display

# Paths
results_dir = "/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPconvBi_100/detect/predict/predict"
ground_truth_dir = "/content/drive/MyDrive/ComputerVisionBat/BatDetection.yolov8/test/labels"

# List images
image_files = [f for f in os.listdir(results_dir) if f.endswith((".jpg", ".png"))]

for img_file in image_files[:10]:
    img_path = os.path.join(results_dir, img_file)
    img = Image.open(img_path)
    draw = ImageDraw.Draw(img)

    # Ground truth boxes
    label_file = os.path.join(ground_truth_dir, os.path.splitext(img_file)[0] + ".txt")
    if os.path.exists(label_file):
        with open(label_file, "r") as f:
            for line in f.readlines():
                class_id, x_center, y_center, width, height = map(float, line.strip().split())
                img_w, img_h = img.size
                x0 = (x_center - width / 2) * img_w
                y0 = (y_center - height / 2) * img_h
                x1 = (x_center + width / 2) * img_w
                y1 = (y_center + height / 2) * img_h
                draw.rectangle([x0, y0, x1, y1], outline="red", width=2)

    # Predicted boxes
    pred_txt_file = os.path.join(results_dir, os.path.splitext(img_file)[0] + ".txt")
    if os.path.exists(pred_txt_file):
        with open(pred_txt_file, "r") as f:
            for line in f.readlines():
                parts = list(map(float, line.strip().split()))
                if len(parts) == 5:
                    class_id, x_center, y_center, width, height = parts
                elif len(parts) == 6:
                    class_id, x_center, y_center, width, height, conf = parts
                else:
                    continue

                img_w, img_h = img.size
                x0 = (x_center - width / 2) * img_w
                y0 = (y_center - height / 2) * img_h
                x1 = (x_center + width / 2) * img_w
                y1 = (y_center + height / 2) * img_h
                draw.rectangle([x0, y0, x1, y1], outline="green", width=2)

    display(img)

"""# YOLOV8m with **AdaptiveThresholdFocalLoss**"""

!pip install -U ultralytics

from ultralytics import YOLO

model = YOLO('/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/models/v8/yolov8m-p2p.yaml')

# Train the model
train_results = model.train(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    epochs=100,
    batch=1,
    patience = 20, amp=False,
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_ATFL"
)

from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_ATFL/train/weights/last.pt")

model.train(resume=True, device='cpu')

import torch
print("CUDA available:", torch.cuda.is_available())
print("Device name:", torch.cuda.get_device_name(0))

from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_ATFL/train/weights/last.pt")

model.train(resume=True)

"""**Validation**"""

from ultralytics import YOLO

# Load your trained model (best.pt from training)
model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_ATFL/train/weights/best.pt")

# Run evaluation on the validation set
val_metrics = model.val(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    batch=1,
    show_labels=False,
    show_conf=False,
    project = "/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_ATFL/detect"
)

"""**Inference**"""

from ultralytics import YOLO
model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_ATFL/train/weights/best.pt")
result = model.predict(source="/content/drive/MyDrive/ComputerVisionBat/BatDetection.yolov8/test/images",
    conf=0.25,
    batch=1,
    show_labels=False,
    show_conf=False,
    save=True,
    project = "/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_ATFL/detect",
                       save_txt = True
)

import os
from PIL import Image, ImageDraw
from IPython.display import display

# Paths
results_dir = "/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_ATFL/detect/predict2"
ground_truth_dir = "/content/drive/MyDrive/ComputerVisionBat/BatDetection.yolov8/test/labels"

# List images
image_files = [f for f in os.listdir(results_dir) if f.endswith((".jpg", ".png"))]

for img_file in image_files[:10]:
    img_path = os.path.join(results_dir, img_file)
    img = Image.open(img_path)
    draw = ImageDraw.Draw(img)

    # Ground truth boxes
    label_file = os.path.join(ground_truth_dir, os.path.splitext(img_file)[0] + ".txt")
    if os.path.exists(label_file):
        with open(label_file, "r") as f:
            for line in f.readlines():
                class_id, x_center, y_center, width, height = map(float, line.strip().split())
                img_w, img_h = img.size
                x0 = (x_center - width / 2) * img_w
                y0 = (y_center - height / 2) * img_h
                x1 = (x_center + width / 2) * img_w
                y1 = (y_center + height / 2) * img_h
                draw.rectangle([x0, y0, x1, y1], outline="red", width=2)

    # Predicted boxes
    pred_txt_file = os.path.join(results_dir, os.path.splitext(img_file)[0] + ".txt")
    if os.path.exists(pred_txt_file):
        with open(pred_txt_file, "r") as f:
            for line in f.readlines():
                parts = list(map(float, line.strip().split()))
                if len(parts) == 5:
                    class_id, x_center, y_center, width, height = parts
                elif len(parts) == 6:
                    class_id, x_center, y_center, width, height, conf = parts
                else:
                    continue

                img_w, img_h = img.size
                x0 = (x_center - width / 2) * img_w
                y0 = (y_center - height / 2) * img_h
                x1 = (x_center + width / 2) * img_w
                y1 = (y_center + height / 2) * img_h
                draw.rectangle([x0, y0, x1, y1], outline="green", width=2)

    display(img)

"""**Metrics**"""

from IPython.display import Image, display

display(Image("/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_ATFL/detect/val/confusion_matrix.png"))

mp, mr, map50, map = val_metrics.mean_results()

print(f"Precision: {mp:.4f}")
print(f"Recall: {mr:.4f}")
print(f"mAP@0.5: {map50:.4f}")
print(f"mAP@0.5:0.95: {map:.4f}")

"""When epoch 21 to 100:
* Precision: 0.7787
* Recall: 0.5939
* mAP@0.5: 0.6548
* mAP@0.5:0.95: 0.3179

Metrics after using yolov8m with Pconv

* Precision: 0.7974
* Recall: 0.5957
* mAP@0.5: 0.6570
* mAP@0.5:0.95: 0.3176
"""

# graph

"""For yolov8m model with Pconv and ATFL:
* Precision: 0.7643
* Recall: 0.5600
* mAP@0.5: 0.6305
* mAP@0.5:0.95: 0.3032

# Yolov8 +PConv+C3fGhost
"""

from ultralytics import YOLO

model = YOLO('/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/models/v8/yolov8n_PconvGhost.yaml')

# Train the model
train_results = model.train(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    epochs=100,
    batch=1,
    patience = 20,
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_nPConvGhost"
)

"""**Validation Yolov8n + PConv+ C3fGhost**"""

from ultralytics import YOLO

# Load your trained model (best.pt from training)
model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_nPConvGhost/train/weights/best.pt")

# Run evaluation on the validation set
val_metrics = model.val(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    batch=1,
    show_labels=False,
    show_conf=False,
    save_json=True,         # saves results in COCO-style JSON (detections)
    save_txt=True,          # saves detection boxes in YOLO txt format
    save=True,
    project = "/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_nPConvGhost/detect"
)

from ultralytics import YOLO

# Load your trained model (best.pt from training)
model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_nPConvGhost/train/weights/best.pt")
result = model.predict(source="/content/drive/MyDrive/ComputerVisionBat/BatDetection.yolov8/test/images",
    conf=0.25,
    batch=1,
    show_labels=False,
    show_conf=False,
    save=True,
    project = "/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_nPConvGhost/detect",
                       save_txt = True
)



"""# Yolov8m + PConv + C3fGhost"""

from ultralytics import YOLO

model = YOLO('/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/models/v8/yolov8m_PconvGhost.yaml')

# Train the model
train_results = model.train(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    epochs=100,
    batch=1,
    patience = 20,
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPConvGhost"
)



from ultralytics import YOLO

# Load your trained model (best.pt from training)
model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPConvGhost/train/weights/best.pt")

# Run evaluation on the validation set
val_metrics = model.val(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    batch=1,
    show_labels=False,
    show_conf=False,
    save_json=True,         # saves results in COCO-style JSON (detections)
    save_txt=True,          # saves detection boxes in YOLO txt format
    save=True,
    project = "/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPConvGhost/detect"
)

from ultralytics import YOLO
model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPConvGhost/train/weights/best.pt")
result = model.predict(source="/content/drive/MyDrive/ComputerVisionBat/BatDetection.yolov8/test/images",
    conf=0.25,
    batch=1,
    show_labels=False,
    show_conf=False,
    save=True,
    project = "/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPConvGhost/detect",
                       save_txt = True
)



from ultralytics import YOLO

model = YOLO('/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/models/v8/yolov8n-ghost-p2.yaml')

# Train the model
train_results = model.train(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    epochs=100,
    batch=1,
    patience = 20,
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mod-nGhost"
)

from ultralytics import YOLO

# Load your trained model (best.pt from training)
model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_nGhost/train/weights/best.pt")

# Run evaluation on the validation set
val_metrics = model.val(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    batch=1,
    show_labels=False,
    show_conf=False,
    project = "/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_nGhost/detect"
)

from ultralytics import YOLO

# Load your trained model (best.pt from training)
model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_nGhost/train/weights/best.pt")
result = model.predict(source="/content/drive/MyDrive/ComputerVisionBat/BatDetection.yolov8/test/images",
    conf=0.25,
    batch=1,
    show_labels=False,
    show_conf=False,
    save=True,
    project = "/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_nGhost/detect",
                       save_txt = True
)

"""# YOLOV8+ PConv+CBAM with bilinear


"""

from ultralytics import YOLO

model = YOLO('/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/models/v8/yolov8m_PconvCBAM.yaml')

# Train the model
train_results = model.train(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    epochs=100,
    batch=1,
    patience = 20,
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPConvCBAM"
)

from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPConvCBAM/train/weights/last.pt")

model.train(resume=True)

from ultralytics import YOLO

# Load your trained model (best.pt from training)
model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPConvCBAM_Bi/train/weights/best.pt")

# Run evaluation on the validation set
val_metrics = model.val(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    batch=1,
    show_labels=False,
    show_conf=False,
    save_json=True,         # saves results in COCO-style JSON (detections)
    save_txt=True,          # saves detection boxes in YOLO txt format
    save=True,
    project = "/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPConvCBAM_Bi/detect"
)

#predict
from ultralytics import YOLO

# Load your trained model (best.pt from training)
model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPConvCBAM_Bi/train/weights/best.pt")
result = model.predict(source="/content/drive/MyDrive/ComputerVisionBat/BatDetection.yolov8/test/images",
    conf=0.25,
    batch=1,
    show_labels=False,
    show_conf=False,
    save=True,
    project = "/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPConvCBAM_Bi/detect",
                       save_txt = True
)

# /content/drive/MyDrive/ComputerVisionBat/ultralyticsFinal/runs_nPConvGhost/detect/predict


# /content/drive/MyDrive/ComputerVisionBat/ultralyticsFinal/runs_mPconvBi_100/detect/predict
# /content/drive/MyDrive/ComputerVisionBat/ultralyticsFinal/runs_mPConvCBAM_Bi/detect/predict

# /content/drive/MyDrive/ComputerVisionBat/ultralyticsFinal/runs_mPConvCBAM_nearest/detect/predict
# /content/drive/MyDrive/ComputerVisionBat/ultralytics/runsmpconv_ATFL/detect/predict

# /content/drive/MyDrive/ComputerVisionBat/BatDetection.yolov8/test/labels file with labesl
# yolov8n: /content/drive/MyDrive/BatDetection.yolov8/runs_stop/detect/predict/predict
# yolov8m pconv: /content/drive/MyDrive/ComputerVisionBat/ultralyticsWorking/runs_mPconv/predict
# /content/drive/MyDrive/ComputerVisionBat/ultralyticsWorking/runs_nPconv/detect/predict

"""# YOLOV8+ PConv+CBAM with nearest"""

from ultralytics import YOLO

model = YOLO('/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/models/v8/yolov8m_PconvCBAM.yaml')

# Train the model
train_results = model.train(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    epochs=100,
    batch=1,
    patience = 20,
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPConvCBAM_nearest"
)

from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPConvCBAM_nearest/train/weights/last.pt")

model.train(resume=True)

from ultralytics import YOLO

# Load your trained model (best.pt from training)
model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPConvCBAM_nearest/train/weights/best.pt")

# Run evaluation on the validation set
val_metrics = model.val(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    batch=1,
    show_labels=False,
    show_conf=False,
    save_json=True,         # saves results in COCO-style JSON (detections)
    save_txt=True,          # saves detection boxes in YOLO txt format
    save=True,
    project = "/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPConvCBAM_nearest/detect/val_30"
)

mAP30 = val_metrics.box.all_ap[:, 6].mean()
print("mAP@0.30:", mAP30.item())

mAP50 = val_metrics.box.all_ap[:, 10].mean()
print("mAP@0.50:", mAP50.item())

from ultralytics import YOLO

# Load your trained model (best.pt from training)
model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPConvCBAM_nearest/train/weights/best.pt")
result = model.predict(source="/content/drive/MyDrive/ComputerVisionBat/BatDetection.yolov8/test/images",
    conf=0.25,
    batch=1,
    show_labels=False,
    show_conf=False,
    save=True,
    project = "/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPConvCBAM_nearest/detect",
                       save_txt = True
)

# mPconv atfl - /content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_ATFL/detect/predict2/labels

# mpconv cbamBi /content/drive/MyDrive/ComputerVisionBat/ultralyticsFinal/runs_mPConvCBAM_Bi/detect/predict2/labels

# mpconvcbam Bi /content/drive/MyDrive/ComputerVisionBat/ultralyticsFinal/runs_mPConvCBAM_Bi/detect/predict2
# mpconvcbam_nearest /content/drive/MyDrive/ComputerVisionBat/ultralyticsFinal/runs_mPConvCBAM_nearest/detect/predict2/labels
# MPconvBi100
# mpconvghost:
# runs_mPconvBi /content/drive/MyDrive/ComputerVisionBat/ultralyticsFinal/runs_mPconvBi/detect/predict2/labels
# npconv ghost /content/drive/MyDrive/ComputerVisionBat/ultralyticsFinal/runs_nPConvGhost/detect/predict2/labels

"""# Training & Validation Curves"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from glob import glob

# Make plots look nice
sns.set(style="whitegrid", font_scale=1.2)
plt.rcParams['figure.figsize'] = (8, 5)

# paths to your model results
models = {
    # "YOLOv8n": "/content/drive/MyDrive/BatDetection.yolov8/runs_stop/detect/train/results.csv",
    # "YOLOv8n+PConv": "/content/drive/MyDrive/ComputerVisionBat/ultralyticsWorking/runs_nPconv/detect/train/results.csv",
    "YOLOv8m+PConv" : "/content/drive/MyDrive/ComputerVisionBat/ultralyticsWorking/runs_mPconv/train/results.csv",
    "YOLOv8m + PConvBi": "/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPconvBi/train/results.csv",
    "YOLOv8m+C3fGhost": "/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPConvGhost/train/results.csv",
    # "YOLOv8n+C3fGhost": "/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_nPConvGhost/train/results.csv",
    "YOLOV8m+CBAM": "/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPConvCBAM_nearest/train/results.csv",
    "YOLOV8m+CBAMBi":"/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPConvCBAM_Bi/train/results.csv"
}

dfs = {name: pd.read_csv(path) for name, path in models.items()}

import pandas as pd
import matplotlib.pyplot as plt

# paths to your model results
select_models = {
    "YOLOv8m+PConv_100_0.001" : "/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconv100_0.001/train/results.csv",
    "YOLOv8m + PConvBi_100_0.001": "/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconvBi100_0.001/train2/results.csv",
    "YOLOv8m + PConvBi_200_0.001": "/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconvBi200_0.001/train/results.csv",

    "YOLOv8m+PConv_200_0.001": "/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconv200_0.001/train/results.csv",
    "YOLOV8m+CBAM_200_0.002": "/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_PconvCBAM200_0.002/train3/results.csv",
    "YOLOV8m+ATFL_200_0.001":"/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_ATFL200_0.001/train/results.csv"
}

dfs = {name: pd.read_csv(path) for name, path in select_models.items()}

for model_name, df in dfs.items():

    required_cols = [
        "train/cls_loss", "val/cls_loss",
        # "train/dfl_loss", "val/dfl_loss"
    ]

    # Check missing cols
    missing = [c for c in required_cols if c not in df.columns]
    if missing:
        print(f"⚠ Missing columns in {model_name}: {missing}")
        continue

    epochs = range(len(df))


    plt.figure(figsize=(10, 5))
    plt.plot(epochs, df["train/cls_loss"], label="Train CLS Loss", color="blue")
    plt.plot(epochs, df["val/cls_loss"], label="Val CLS Loss", color="red")
    plt.title(f"{model_name} — Classification Loss (CLS)")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()
    plt.show()

import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/ComputerVisionBat/ultralyticsWorking/runs_mPconv/train/results.csv")
print(df.columns.tolist())
df.tail(3)

summary = []
for name, df in dfs.items():
    summary.append({
        "Model": name,
        "Precision": df["metrics/precision"].iloc[-1],
        "Recall": df["metrics/recall"].iloc[-1],
        "mAP@0.5": df["metrics/mAP50"].iloc[-1]
    })

summary_df = pd.DataFrame(summary).set_index("Model")
summary_df.plot(kind="bar", color=["#1f77b4", "#ff7f0e", "#2ca02c"])
plt.ylabel("Score")
plt.title("Model Performance Comparison")
plt.ylim(0, 1)
plt.show()

plt.figure(figsize=(10, 6))
sns.set(style="whitegrid")

for name, df in dfs.items():
    plt.plot(df["epoch"], df["train/box_loss"], label=f"{name} - train", linestyle="-")

plt.title("Training Loss per Epoch")
plt.xlabel("Epoch")
plt.ylabel("Box Loss")
plt.legend()
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Model variants (use readable names for figure)
models = [
    "YOLOv8n",
    "YOLOv8n + PConv",
    "YOLOv8m + PConv (nearest)",
    "YOLOv8m + PConv (bilinear)",
    "YOLOv8n + PConv + C3fGhost",
    "YOLOv8m + PConv + C3fGhost",
    "YOLOv8m + PConv + CBAM (nearest)",
    "YOLOv8m + PConv + CBAM (bilinear)",
    "YOLOv8m + PConv + ATFL"
]

# Metrics
precision = [0.631, 0.727, 0.797, 0.768, 0.626, 0.747, 0.718, 0.736, 0.764]
recall    = [0.462, 0.518, 0.596, 0.605, 0.492, 0.576, 0.591, 0.585, 0.560]
mAP50     = [0.488, 0.638, 0.657, 0.656, 0.490, 0.625, 0.628, 0.624, 0.631]

# X locations
x = np.arange(len(models))
width = 0.25

# Create plot
fig, ax = plt.subplots(figsize=(14,6))
rects1 = ax.bar(x - width, precision, width, label='Precision', color='#1f77b4')
rects2 = ax.bar(x, recall, width, label='Recall', color='#ff7f0e')
rects3 = ax.bar(x + width, mAP50, width, label='mAP@0.5', color='#2ca02c')


ax.set_ylabel('Score', fontsize=14)
ax.set_title('Comparison of Detection Performance', fontsize=16, fontweight='bold')
ax.set_xticks(x)
ax.set_xticklabels(models, rotation=30, ha='right', fontsize=14, fontweight='bold')
ax.set_ylim(0, 1)
ax.legend(fontsize=12)


# Add values on top of bars
for rects in [rects1, rects2, rects3]:
    for rect in rects:
        height = rect.get_height()
        ax.annotate(f'{height:.2f}',
                    xy=(rect.get_x() + rect.get_width() / 2, height),
                    xytext=(0, 3),
                    textcoords="offset points",
                    ha='center', va='bottom', fontsize=8)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Only YOLOv8m variants
models_m = [
    "YOLOv8m + PConv (nearest)",
    "YOLOv8m + PConv (bilinear)",
    "YOLOv8m + PConv + C3fGhost",
    "YOLOv8m + PConv + CBAM (nearest)",
    "YOLOv8m + PConv + CBAM (bilinear)",
    "YOLOv8m + PConv + ATFL"
]

# Metrics
precision_m = [0.797, 0.768, 0.747, 0.718, 0.736, 0.764]
recall_m    = [0.596, 0.605, 0.576, 0.591, 0.585, 0.560]
mAP50_m     = [0.657, 0.656, 0.625, 0.628, 0.624, 0.631]

# X locations
x = np.arange(len(models_m))
width = 0.25

# Create plot
fig, ax = plt.subplots(figsize=(12,5))
rects1 = ax.bar(x - width, precision_m, width, label='Precision', color='#1f77b4')
rects2 = ax.bar(x, recall_m, width, label='Recall', color='#ff7f0e')
rects3 = ax.bar(x + width, mAP50_m, width, label='mAP@0.5', color='#2ca02c')

# Labels and title
ax.set_ylabel('Score')
ax.set_title('Ablation Study: YOLOv8m Variants (Thermal IR Bats)')
ax.set_xticks(x)
ax.set_xticklabels(models_m, rotation=30, ha='right')
ax.set_ylim(0,1)
ax.legend()

# Add values on top of bars
for rects in [rects1, rects2, rects3]:
    for rect in rects:
        height = rect.get_height()
        ax.annotate(f'{height:.2f}',
                    xy=(rect.get_x() + rect.get_width() / 2, height),
                    xytext=(0, 3),
                    textcoords="offset points",
                    ha='center', va='bottom', fontsize=8)

plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))
sns.set(style="whitegrid")

for name, df in dfs.items():
        plt.plot(df["epoch"], df["val/box_loss"], label=f"{name} - val")

plt.title("Training Loss per Epoch")
plt.xlabel("Epoch")
plt.ylabel("Box Loss")
plt.legend()
plt.tight_layout()
plt.show()

# Figure 4.1: Comparison of training and validation loss for YOLOv8 variants.

"""YOLOv8m + PConv (Nearest, 200 epochs, LR 0.001) → my main choice

YOLOv8m + PConv (Bilinear, 200 epochs, LR 0.001) → compare upsampling

YOLOv8m + PConv + CBAM (Nearest, 200 epochs, LR 0.001) → effect of attention

YOLOv8m + PConv + ATFL (Nearest, 200 epochs, LR 0.001) → effect of loss function

YOLOv8n + PConv (Nearest, 100 epochs, LR 0.002) → smaller baseline model
"""

# --- Setup ---
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from glob import glob

# Plot style: ML-paper-like aesthetic
sns.set_style("whitegrid")
plt.rcParams.update({
    "font.size": 13,
    "axes.labelsize": 13,
    "axes.titlesize": 14,
    "legend.fontsize": 11,
    "figure.figsize": (7, 5),
    "axes.linewidth": 1.2,
    "xtick.major.size": 4,
    "ytick.major.size": 4
})

# Define paths to your YOLOv8 results
model_paths = {
    "YOLOv8mPConv200_0.001": "/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconv200_0.001/train/results.csv",
    "YOLOv8mPConvBi200_001": "/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconvBi200_0.001/train/results.csv",
    "YOLOv8mPConvCBAM200_0.001" : "/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_PconvCBAM200_0.001/train/results.csv",
    "YOLOv8mPConvATFL200_0.001": "/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_ATFL200_0.001/train/results.csv",
    "YOLOv8n": "/content/drive/MyDrive/BatDetection.yolov8/runs_stop/detect/train/results.csv",
}

dfs = {name: pd.read_csv(path) for name, path in model_paths.items()}

# Helper to find columns even if names vary slightly
def get_col(df, name_list):
    for n in name_list:
        if n in df.columns:
            return df[n]
    raise KeyError(f"None of {name_list} found in {df.columns.tolist()}")

plt.figure(figsize=(10, 6))
sns.set(style="whitegrid")

for name, df in dfs.items():
        plt.plot(df["epoch"], df["val/box_loss"], label=f"{name} - val")

plt.title("Training Loss per Epoch")
plt.xlabel("Epoch")
plt.ylabel("Box Loss")
plt.legend()
plt.tight_layout()
plt.show()

# --- Plot training and validation total loss individually ---
for name, df in dfs.items():
    # Compute total loss
    # df['train_total_loss'] = df[['train/box_loss', 'train/cls_loss', 'train/dfl_loss']].sum(axis=1)
    # df['val_total_loss']   = df[['val/box_loss', 'val/cls_loss', 'val/dfl_loss']].sum(axis=1)

    # Plot
    plt.figure(figsize=(7,5))
    plt.plot(df['epoch'], df['train/box_loss'], label='Training Loss', color='blue', linewidth=2)
    plt.plot(df['epoch'], df['val/box_loss'], label='Validation Loss', color='orange', linewidth=2)
    plt.title(f'{name} Training vs Validation Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Box Loss')
    plt.legend()
    plt.tight_layout()
    plt.show()

for name, df in dfs.items():
    # Compute total loss
    # df['train_total_loss'] = df[['train/box_loss', 'train/cls_loss', 'train/dfl_loss']].sum(axis=1)
    # df['val_total_loss']   = df[['val/box_loss', 'val/cls_loss', 'val/dfl_loss']].sum(axis=1)

    # Plot
    plt.figure(figsize=(7,5))
    plt.plot(df['epoch'], df['train/cls_loss'], label='Training Loss', color='blue', linewidth=2)
    plt.plot(df['epoch'], df['val/cls_loss'], label='Validation Loss', color='orange', linewidth=2)
    plt.title(f'{name} Training vs Validation Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Total Loss')
    plt.legend()
    plt.tight_layout()
    plt.show()

for name, df in dfs.items():
    precision = get_col(df, ["metrics/precision(B)"])
    recall = get_col(df, ["metrics/recall(B)"])
    f1 = 2 * (precision * recall) / (precision + recall + 1e-8)
    plt.plot(df["epoch"], f1, label=name, linewidth=2.0)

plt.xlabel("Epoch")
plt.ylabel("F1-score")
plt.title("F1-score Progress Across Training")
plt.legend(frameon=True)
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

from IPython.display import Image, display
import os

# Example: display 3 detection outputs from the final model
prediction_dir = "/content/runs/detect/yolov8m_pconv/predictions/"
for img_path in sorted(glob(os.path.join(prediction_dir, "*.jpg")))[:3]:
    display(Image(filename=img_path))



fig, axs = plt.subplots(2, 1, figsize=(8,10))
axs[0].plot(df['epoch'], df['train/box_loss'], label='Train Box Loss')
axs[0].plot(df['epoch'], df['val/box_loss'], label='Val Box Loss')
axs[0].set_title('Box Loss')
axs[0].legend()

axs[1].plot(df['epoch'], df['train/cls_loss'], label='Train CLS Loss')
axs[1].plot(df['epoch'], df['val/cls_loss'], label='Val CLS Loss')
axs[1].set_title('Classification Loss')
axs[1].legend()

plt.show()

model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralyticsWorking/runs_nPconv/detect/train/weights/best.pt")

result = model.predict(source="/content/drive/MyDrive/ComputerVisionBat/BatDetection.yolov8/test/images",
    conf=0.25,
    batch=1,
    show_labels=False,
    show_conf=False,
    save=True,
      save_txt = True,
    project = "/content/drive/MyDrive/ComputerVisionBat/ultralyticsWorking/runs_nPconv/detect/predict"
)



"""# HYPERPARAMETER **TESTING**

# mPConv with **bilinear**
"""

from ultralytics import YOLO

model = YOLO('/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/models/v8/yolov8m-p2p.yaml')

# Train the model
train_results = model.train(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    epochs=50,
    batch=1,
    patience = 15,
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPConv_bilinear"
)

from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPConv_bilinear/train/weights/best.pt")
metrics = model.val(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    batch=1,
    conf=0.25,
    show_labels=False,
    show_conf=False,
    save_json=True,
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPConv_bilinear/detect"
)

mAP30 = metrics.box.all_ap[:, 6].mean()
print("mAP@0.30:", mAP30.item())

model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPConv_bilinear/train/weights/best.pt")

result = model.predict(source="/content/drive/MyDrive/ComputerVisionBat/BatDetection.yolov8/test/images",
    conf=0.25,
    batch=1,
    show_labels=False,
    show_conf=False,
    save=True,
      save_txt = True,
    project = "/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPConv_bilinear/detect"
)

from IPython.display import Image, display

display(Image("/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPConv_bilinear/detect/val/confusion_matrix.png"))

mp, mr, map50, map = metrics.mean_results()

print(f"Precision: {mp:.4f}")
print(f"Recall: {mr:.4f}")
print(f"mAP@0.5: {map50:.4f}")
print(f"mAP@0.5:0.95: {map:.4f}")

from ultralytics import YOLO

# Load the last checkpoint
model =YOLO('/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/models/v8/yolov8m-p2p.yaml')

# Continue training in the same folder
train_results = model.train(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    epochs=200,   # total epochs
    batch=1,
    patience=15,
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconvBi200",
)



from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconvBi200/train/weights/best.pt")
metrics = model.val(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    batch=1,
    conf=0.25,
    show_labels=False,
    show_conf=False,
    save_json=True,
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconvBi200/detect"
)

mAP30 = metrics.box.all_ap[:, 6].mean()
print("mAP@0.30:", mAP30.item())

from ultralytics import YOLO
from re import split
# Load your trained model (best.pt from training)
model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconvBi200_0.002/train/weights/best.pt")

result = model.predict(source="/content/drive/MyDrive/ComputerVisionBat/BatDetection.yolov8/test/images",
    conf=0.25,
    batch=1,
    show_labels=False,
    show_conf=False,
    save=True,
    save_txt=True,
    project = "/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconvBi200_0.002/detect"

)

display(Image("/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPconvBi/detect/val/confusion_matrix.png"))

from IPython.display import Image, display

display(Image("/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconvBi200/detect/val/confusion_matrix.png"))

mp, mr, map50, map = metrics.mean_results()

print(f"Precision: {mp:.4f}")
print(f"Recall: {mr:.4f}")
print(f"mAP@0.5: {map50:.4f}")
print(f"mAP@0.5:0.95: {map:.4f}")

import os
from PIL import Image, ImageDraw
from IPython.display import display

# Paths
results_dir = "/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconvBi200_0.002/detect/predict"
ground_truth_dir = "/content/drive/MyDrive/ComputerVisionBat/BatDetection.yolov8/test/labels"

# List images
image_files = [f for f in os.listdir(results_dir) if f.endswith((".jpg", ".png"))]

for img_file in image_files[:10]:
    img_path = os.path.join(results_dir, img_file)
    img = Image.open(img_path)
    draw = ImageDraw.Draw(img)

    # Draw ground truth boxes
    label_file = os.path.join(ground_truth_dir, os.path.splitext(img_file)[0] + ".txt")
    if os.path.exists(label_file):
        with open(label_file, "r") as f:
            for line in f.readlines():
                class_id, x_center, y_center, width, height = map(float, line.strip().split())
                img_w, img_h = img.size
                x_center *= img_w
                y_center *= img_h
                width *= img_w
                height *= img_h
                x0 = x_center - width / 2
                y0 = y_center - height / 2
                x1 = x_center + width / 2
                y1 = y_center + height / 2
                draw.rectangle([x0, y0, x1, y1], outline="red", width=2)  # Ground truth = red

    # draw YOLO predicted boxes (if predictions are saved in .txt)
    # Draw YOLO predicted boxes
    pred_txt_file = os.path.join(results_dir, "labels", os.path.splitext(img_file)[0] + ".txt")
    if os.path.exists(pred_txt_file):
        with open(pred_txt_file, "r") as f:
            for line in f.readlines():
                parts = list(map(float, line.strip().split()))
                if len(parts) == 5:  # no confidence
                    class_id, x_center, y_center, width, height = parts
                elif len(parts) == 6:  # with confidence
                    class_id, x_center, y_center, width, height, conf = parts
                else:
                    continue  # skip malformed lines

                img_w, img_h = img.size
                x0 = (x_center - width / 2) * img_w
                y0 = (y_center - height / 2) * img_h
                x1 = (x_center + width / 2) * img_w
                y1 = (y_center + height / 2) * img_h
                draw.rectangle([x0, y0, x1, y1], outline="blue", width=2)  # Predicted = blue

    display(img)

from ultralytics import YOLO

# Load model
model = YOLO('/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/models/v8/yolov8m-p2p.yaml')

# Train with custom LR
train_results = model.train(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    epochs=100,
    batch=1,
    patience=20,
    optimizer="AdamW",
    lr0=0.001,
    cos_lr=True,
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconvBi100_0.001",
)

from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconvBi100_0.001/train/weights/best.pt")
metrics = model.val(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    batch=1,
    conf=0.25,
    show_labels=False,
    show_conf=False,
    save_json=True,
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconvBi100_0.001/detect"
)

mAP30 = metrics.box.all_ap[:, 6].mean()
print("mAP@0.30:", mAP30.item())

from ultralytics import YOLO
from re import split
# Load your trained model (best.pt from training)
model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPconvBi_100/train/weights/best.pt")

result = model.predict(source="/content/drive/MyDrive/ComputerVisionBat/BatDetection.yolov8/test/images",
    conf=0.25,
    batch=1,
    show_labels=False,
    show_conf=False,
    save=True,
    save_txt=True,
                       project = "/content/drive/MyDrive/ComputerVisionBat/ultralytics/runs_mPconvBi_100/detect/predict"

)



"""# Hypertuning mYolov8 nearest"""

from ultralytics import YOLO

# Load model
model = YOLO('/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/models/v8/yolov8m-p2p.yaml')

# Train with custom LR
train_results = model.train(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    epochs=200,
    batch=1,
    patience=20,
    # optimizer="AdamW",
    # lr0=0.001,
    cos_lr=True,
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconv200_0.002",
)

from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconv200_0.002/train/weights/last.pt")

model.train(resume=True)

from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconv200_0.002/train/weights/best.pt")
metrics = model.val(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    batch=1,
    conf=0.25,
    show_labels=False,
    show_conf=False,
    save_json=True,
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconv200_0.002/detect"
)

mAP30 = metrics.box.all_ap[:, 6].mean()
print("mAP@0.30:", mAP30.item())



from ultralytics import YOLO

# Load model
model = YOLO('/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/models/v8/yolov8m-p2p.yaml')

# Train with custom LR
train_results = model.train(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    epochs=100,
    batch=1,
    patience=20,
    optimizer="AdamW",
    lr0=0.001,
    cos_lr=True,
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconv100_0.001",
)

from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconv100_0.001/train/weights/last.pt")

model.train(resume=True)

from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconv100_0.001/train/weights/best.pt")
metrics = model.val(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    batch=1,
    conf=0.25,
    show_labels=False,
    show_conf=False,
    save_json=True,
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconv100_0.001/detect"
)
mAP30 = metrics.box.all_ap[:, 6].mean()
print("mAP@0.30:", mAP30.item())



from ultralytics import YOLO

# Load model
model = YOLO('/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/models/v8/yolov8m-p2p.yaml')

# Train with custom LR
train_results = model.train(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    epochs=200,
    batch=1,
    patience=20,
    optimizer="AdamW",
    lr0=0.001,
    cos_lr=True,
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconv200_0.001",
)

from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconv200_0.001/train/weights/best.pt")
metrics = model.val(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    batch=1,
    conf=0.25,
    show_labels=False,
    show_conf=False,
    save_json=True,
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconv200_0.001/detect"
)
mAP30 = metrics.box.all_ap[:, 6].mean()
print("mAP@0.30:", mAP30.item())



"""Hyperparameter mPConv CBAM nearest

"""

from ultralytics import YOLO

# Load model
model = YOLO('/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/models/v8/yolov8m_PconvCBAM.yaml')

# Train with custom LR
train_results = model.train(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    epochs=200,
    batch=1,
    patience=20,
    # optimizer="AdamW",
    # lr0=0.001,
    # amp=False,?
    # cos_lr=True,
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_PconvCBAM200_0.002",
)

from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_PconvCBAM200_0.002/train3/weights/last.pt")

model.train(resume=True)

from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_PconvCBAM200_0.002/train3/weights/best.pt")
metrics = model.val(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    batch=1,
    conf=0.25,
    show_labels=False,
    show_conf=False,
    save_json=True,
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_PconvCBAM200_0.002/detect"
)
mAP30 = metrics.box.all_ap[:, 6].mean()
print("mAP@0.30:", mAP30.item())



from ultralytics import YOLO

# Load model
model = YOLO('/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/models/v8/yolov8m_PconvCBAM.yaml')

# Train with custom LR
train_results = model.train(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    epochs=200,
    batch=1,
    patience=20,
    optimizer="AdamW",
    lr0=0.001,
    # cos_lr=True,
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_PconvCBAM200_0.001",
)

from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_PconvCBAM200_0.001/train/weights/best.pt")
metrics = model.val(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    batch=1,
    conf=0.25,
    show_labels=False,
    show_conf=False,
    save_json=True,
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_PconvCBAM200_0.001/detect"
)
mAP30 = metrics.box.all_ap[:, 6].mean()
print("mAP@0.30:", mAP30.item())



"""# **ATFL**"""

from ultralytics import YOLO

model = YOLO('/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/models/v8/yolov8m-p2p.yaml')

# Train the model
train_results = model.train(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    epochs=200,
    batch=1,
    patience = 20, amp=False,
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_ATFL200_0.002"
)

from ultralytics import YOLO
ultralytics
model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_ATFL200_0.002/train/weights/last.pt")

model.train(resume=True)

from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_ATFL200_0.002/train/weights/best.pt")
metrics = model.val(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    batch=1,
    conf=0.25,
    show_labels=False,
    show_conf=False,
    save_json=True,
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_ATFL200_0.002/detect"
)
mAP30 = metrics.box.all_ap[:, 6].mean()
print("mAP@0.30:", mAP30.item())



from ultralytics import YOLO

model = YOLO('/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/models/v8/yolov8m-p2p.yaml')

# Train the model
train_results = model.train(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    epochs=200,
    batch=1,
    optimizer="AdamW",
    lr0=0.001,
    patience = 20, amp=False,
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_ATFL200_0.001"
)

from ultralytics import YOLO

model = YOLO("/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_ATFL200_0.001/train/weights/best.pt")
metrics = model.val(
    data="/content/drive/MyDrive/ComputerVisionBat/ultralytics/ultralytics/cfg/datasets/data.yaml",
    batch=1,
    conf=0.25,
    show_labels=False,
    show_conf=False,
    save_json=True,
    project="/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_ATFL200_0.001/detect"
)

from ultralytics import YOLO

model = YOLO('/content/drive/MyDrive/BatDetection.yolov8/runs_stop/detect/train/weights/best.pt')

metrics = model.predict(source="/content/drive/MyDrive/ComputerVisionBat/BatDetection.yolov8/test/images",
    conf=0.25,
    batch=1,
    show_labels=False,
    show_conf=False,
    save=True,
                        save_json = True,
    project="/content/drive/MyDrive/BatDetection.yolov8/runs_stop/detect/predict-new",
    save_txt = True
)

for name, path in model_paths.items():
    count = 0
    for f in os.listdir(path):
        if f.endswith(".txt"):
            count += sum(1 for _ in open(os.path.join(path, f)))
    print(f"{name}: total predicted boxes = {count}")

gt_total = sum(sum(1 for _ in open(os.path.join(gt_path, f))) for f in os.listdir(gt_path))
print("Ground truth total boxes:", gt_total)



from ultralytics import YOLO

# Define models and their save directories
models_info = {
    "YOLOv8-M + PConv Nearest": {
        "path": "/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconv200_0.001/train/weights/best.pt",
        "save_dir": "/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconv200_0.001/detect"
    }
    # "YOLOv8m + PConv + CBAM": {
    #     "path": "/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_PconvCBAM200_0.002/train3/weights/best.pt",
    #     "save_dir": "/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_PconvCBAM200_0.002/detect/predict"
    # },
    # "YOLOv8m + PConv Nearest ATFL": {
    #     "path": "/content/drive/MyDrive/ComputerVisionBat/ultralytics_ATFL/hyperparameter/runs_ATFL200_0.001/train/weights/best.pt",
    #     "save_dir": "/content/drive/MyDrive/ComputerVisionBat/ultralytics_ATFL/hyperparameter/runs_ATFL200_0.001/detect/predict"
    # }
}

test_images = "/content/drive/MyDrive/ComputerVisionBat/BatDetection.yolov8/test/images"

# Loop through all models and predict
for model_name, info in models_info.items():
    print(f"Predicting for {model_name}...")
    model = YOLO(info["path"])
    model.predict(
        source=test_images,
        conf=0.25,
        batch=1,
        show_labels=False,
        show_conf=False,
        save=True,
        save_txt=True,
        project=info["save_dir"]
    )



import os
from PIL import Image, ImageDraw
from IPython.display import display

# CLEAN TEST IMAGES
images_dir = "/content/drive/MyDrive/ComputerVisionBat/BatDetection.yolov8/test/images"

# PREDICTION LABELS ONLY
pred_txt_dir = "/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconv200_0.001/detect/predict/labels"

# GROUND TRUTH LABELS
ground_truth_dir = "/content/drive/MyDrive/ComputerVisionBat/BatDetection.yolov8/test/labels"

# List test images
image_files = [f for f in os.listdir(images_dir) if f.endswith((".jpg", ".png"))]

for img_file in image_files[:50]:

    img_path = os.path.join(images_dir, img_file)
    img = Image.open(img_path)
    draw = ImageDraw.Draw(img)

    # Draw ground truth boxes (red)
    gt_file = os.path.join(ground_truth_dir, os.path.splitext(img_file)[0] + ".txt")
    if os.path.exists(gt_file):
        with open(gt_file, "r") as f:
            for line in f.readlines():
                class_id, x_center, y_center, width, height = map(float, line.strip().split())
                img_w, img_h = img.size
                x0 = (x_center - width/2) * img_w
                y0 = (y_center - height/2) * img_h
                x1 = (x_center + width/2) * img_w
                y1 = (y_center + height/2) * img_h
                draw.rectangle([x0, y0, x1, y1], outline="red", width=2)

    # Draw prediction boxes (green)
    pred_file = os.path.join(pred_txt_dir, os.path.splitext(img_file)[0] + ".txt")
    if os.path.exists(pred_file):
        with open(pred_file, "r") as f:
            for line in f.readlines():
                vals = line.strip().split()
                if len(vals) == 6:
                    class_id, x_center, y_center, width, height, conf = map(float, vals)
                else:
                    class_id, x_center, y_center, width, height = map(float, vals)

                img_w, img_h = img.size
                x0 = (x_center - width/2) * img_w
                y0 = (y_center - height/2) * img_h
                x1 = (x_center + width/2) * img_w
                y1 = (y_center + height/2) * img_h
                draw.rectangle([x0, y0, x1, y1], outline="green", width=2)

    display(img)

def compute_iou(box1, box2):
    # box format: [x0, y0, x1, y1]
    xA = max(box1[0], box2[0])
    yA = max(box1[1], box2[1])
    xB = min(box1[2], box2[2])
    yB = min(box1[3], box2[3])

    interArea = max(0, xB - xA) * max(0, yB - yA)
    if interArea == 0:
        return 0

    box1Area = (box1[2] - box1[0]) * (box1[3] - box1[1])
    box2Area = (box2[2] - box2[0]) * (box2[3] - box2[1])

    return interArea / float(box1Area + box2Area - interArea)

def load_boxes(txt_file, img_w, img_h):
    boxes = []
    with open(txt_file, "r") as f:
        for line in f.readlines():
            vals = line.strip().split()
            if len(vals) >= 5:
                _, xc, yc, w, h = map(float, vals[:5])
                x0 = (xc - w/2) * img_w
                y0 = (yc - h/2) * img_h
                x1 = (xc + w/2) * img_w
                y1 = (yc + h/2) * img_h
                boxes.append([x0, y0, x1, y1])
    return boxes



images_dir = "/content/drive/MyDrive/ComputerVisionBat/BatDetection.yolov8/test/images"
pred_txt_dir = "/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconv200_0.001/detect/predict/labels"
ground_truth_dir = "/content/drive/MyDrive/ComputerVisionBat/BatDetection.yolov8/test/labels"

IOU_THRESHOLD = 0.5
image_metrics = {}

image_files = [f for f in os.listdir(images_dir) if f.endswith((".jpg", ".png"))]

for img_file in image_files:
    img_path = os.path.join(images_dir, img_file)
    img = Image.open(img_path)
    w, h = img.size

    gt_file = os.path.join(ground_truth_dir, img_file.replace(".jpg", ".txt").replace(".png", ".txt"))
    pred_file = os.path.join(pred_txt_dir, img_file.replace(".jpg", ".txt").replace(".png", ".txt"))

    gt_boxes = load_boxes(gt_file, w, h)
    pred_boxes = load_boxes(pred_file, w, h)

    if len(gt_boxes) == 0:
        continue

    TPs = 0
    per_gt_iou = []

    for g in gt_boxes:
        best_iou = max([compute_iou(g, p) for p in pred_boxes], default=0)
        if best_iou >= IOU_THRESHOLD:
            TPs += 1
        per_gt_iou.append(best_iou)

    FP = max(0, len(pred_boxes) - TPs)
    FN = len(gt_boxes) - TPs

    precision = TPs / (TPs + FP) if (TPs + FP) else 0
    recall = TPs / (TPs + FN) if (TPs + FN) else 0
    mean_iou = sum(per_gt_iou) / len(per_gt_iou)
    f1 = 2 * precision * recall / (precision + recall + 1e-9)

    image_metrics[img_file] = {
        "precision": precision,
        "recall": recall,
        "iou": mean_iou,
        "f1": f1
    }

image_metrics = {}

for img_file in image_files:
    img_path = os.path.join(images_dir, img_file)
    img = Image.open(img_path)
    w, h = img.size

    gt_file = os.path.join(ground_truth_dir, img_file.replace(".jpg", ".txt").replace(".png", ".txt"))
    pred_file = os.path.join(pred_txt_dir, img_file.replace(".jpg", ".txt").replace(".png", ".txt"))

    gt_boxes = load_boxes(gt_file, w, h)
    pred_boxes = load_boxes(pred_file, w, h)

    if len(gt_boxes) == 0:
        continue

    TPs = 0
    per_gt_iou = []

    for g in gt_boxes:
        best_iou = max([compute_iou(g, p) for p in pred_boxes], default=0)
        if best_iou >= IOU_THRESHOLD:
            TPs += 1
        per_gt_iou.append(best_iou)

    FP = max(0, len(pred_boxes) - TPs)
    FN = len(gt_boxes) - TPs

    precision = TPs / (TPs + FP) if (TPs + FP) else 0
    recall = TPs / (TPs + FN) if (TPs + FN) else 0
    mean_iou = sum(per_gt_iou) / len(per_gt_iou)
    f1 = 2 * precision * recall / (precision + recall + 1e-9)

    image_metrics[img_file] = {
        "precision": precision,
        "recall": recall,
        "iou": mean_iou,
        "f1": f1,
        "num_gt": len(gt_boxes)  # store number of Ground Truth objects
    }

# Sort by F1, then by number of GT boxes (descending)
sorted_images = sorted(
    image_metrics.items(),
    key=lambda x: (x[1]["f1"], x[1]["num_gt"]),
    reverse=True
)

# Pick top 10
top10_images = sorted_images[:10]
for idx, (img_name, metrics) in enumerate(top10_images, 1):
    print(f"{idx}. {img_name} | F1: {metrics['f1']:.3f}, Recall: {metrics['recall']:.3f}, Precision: {metrics['precision']:.3f}, IoU: {metrics['iou']:.3f}, Num GT: {metrics['num_gt']}")

for img_name, metrics in top10_images:
    img_path = os.path.join(images_dir, img_name)
    img = Image.open(img_path)
    draw = ImageDraw.Draw(img)
    w, h = img.size

    # Draw GT boxes
    gt_file = os.path.join(ground_truth_dir, img_name.replace(".jpg", ".txt").replace(".png", ".txt"))
    gt_boxes = load_boxes(gt_file, w, h)
    for x0, y0, x1, y1 in gt_boxes:
        draw.rectangle([x0, y0, x1, y1], outline="red", width=3)

    # Draw Pred boxes
    pred_file = os.path.join(pred_txt_dir, img_name.replace(".jpg", ".txt").replace(".png", ".txt"))
    pred_boxes = load_boxes(pred_file, w, h)
    for x0, y0, x1, y1 in pred_boxes:
        draw.rectangle([x0, y0, x1, y1], outline="green", width=3)

    print(f"Displaying: {img_name} | GT: {len(gt_boxes)}, Pred: {len(pred_boxes)}")
    display(img)



"""# Qualitative analysis"""

from PIL import Image, ImageDraw
from IPython.display import display
import os

# Define the top images to compare
top_images = [
    "20250123_tile_7_2_png.rf.5332281f10b4b69abe74fc04c8f59cd8.jpg",
    "20250121_Maalan_M350_6am_30m_tile_6_1_png.rf.194bb8891eccbdab95212a8d9511bebc.jpg"
]

# Model paths for prediction labels
models_dirs = {
    "YOLOv8-M + PConv Nearest": "/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_mPconv200_0.001/detect/predict/labels",
    "YOLOv8m + PConv + CBAM": "/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_PconvCBAM200_0.002/detect/predict/predict/labels",
    "YOLOv8m + PConv Nearest ATFL": "/content/drive/MyDrive/ComputerVisionBat/ultralytics/hyperparameter/runs_ATFL200_0.001/detect/predict/predict3/labels"
}

# Ground truth path
ground_truth_dir = "/content/drive/MyDrive/ComputerVisionBat/BatDetection.yolov8/test/labels"

# IoU threshold for Precision and Recall calculation
IOU_THRESHOLD = 0.6

# Function to load bounding boxes
def load_boxes(txt_file, w, h):
    boxes = []
    if not os.path.exists(txt_file):
        return boxes
    with open(txt_file, "r") as f:
        for line in f.readlines():
            vals = line.strip().split()
            if len(vals) < 5:
                continue
            _, xc, yc, bw, bh = map(float, vals[:5])
            x0 = (xc - bw/2) * w
            y0 = (yc - bh/2) * h
            x1 = (xc + bw/2) * w
            y1 = (yc + bh/2) * h
            boxes.append([x0, y0, x1, y1])
    return boxes

# Function to calculate IoU (Intersection over Union)
def calculate_iou(box1, box2):
    x1, y1, x2, y2 = box1
    x3, y3, x4, y4 = box2
    ix1 = max(x1, x3)
    iy1 = max(y1, y3)
    ix2 = min(x2, x4)
    iy2 = min(y2, y4)
    inter_area = max(0, ix2 - ix1) * max(0, iy2 - iy1)

    area1 = (x2 - x1) * (y2 - y1)
    area2 = (x4 - x3) * (y4 - y3)
    union_area = area1 + area2 - inter_area

    return inter_area / union_area if union_area > 0 else 0

# Function to draw boxes on an image and calculate Precision and Recall
def draw_boxes_and_calculate_metrics(img_name, model_name, pred_dir, gt_dir=ground_truth_dir):
    img_path = os.path.join("/content/drive/MyDrive/ComputerVisionBat/BatDetection.yolov8/test/images", img_name)
    img = Image.open(img_path)
    w, h = img.size
    draw = ImageDraw.Draw(img)

    # Ground truth boxes (red)
    gt_file = os.path.join(gt_dir, img_name.replace(".jpg", ".txt").replace(".png", ".txt"))
    gt_boxes = load_boxes(gt_file, w, h)
    for x0, y0, x1, y1 in gt_boxes:
        draw.rectangle([x0, y0, x1, y1], outline="red", width=3)

    # Predicted boxes (green)
    pred_file = os.path.join(pred_dir, img_name.replace(".jpg", ".txt").replace(".png", ".txt"))
    pred_boxes = load_boxes(pred_file, w, h)
    for x0, y0, x1, y1 in pred_boxes:
        draw.rectangle([x0, y0, x1, y1], outline="green", width=3)

    # Calculate Precision and Recall
    true_positives = 0
    false_positives = 0
    false_negatives = 0

    matched_gt = []
    for pred_box in pred_boxes:
        best_iou = 0
        best_gt_idx = -1
        for i, gt_box in enumerate(gt_boxes):
            if i not in matched_gt:
                iou = calculate_iou(pred_box, gt_box)
                if iou > best_iou:
                    best_iou = iou
                    best_gt_idx = i
        if best_iou >= IOU_THRESHOLD:
            true_positives += 1
            matched_gt.append(best_gt_idx)
        else:
            false_positives += 1

    false_negatives = len(gt_boxes) - true_positives

    precision = true_positives / (true_positives + false_positives) if (true_positives + false_positives) > 0 else 0
    recall = true_positives / (true_positives + false_negatives) if (true_positives + false_negatives) > 0 else 0

    return img, len(gt_boxes), len(pred_boxes), precision, recall

# Function to display comparison for each top image with Ground Truth + Predictions
def display_comparison_for_top_images():
    for img_name in top_images:
        print(f"\n=== Image: {img_name} ===\n")

        # First, create and display Ground Truth Only image
        img_path = os.path.join("/content/drive/MyDrive/ComputerVisionBat/BatDetection.yolov8/test/images", img_name)
        img = Image.open(img_path)
        w, h = img.size
        draw = ImageDraw.Draw(img)

        # Draw Ground Truth (red)
        gt_file = os.path.join(ground_truth_dir, img_name.replace(".jpg", ".txt").replace(".png", ".txt"))
        gt_boxes = load_boxes(gt_file, w, h)
        for x0, y0, x1, y1 in gt_boxes:
            draw.rectangle([x0, y0, x1, y1], outline="red", width=3)

        # Display Ground Truth Only
        display(img)

        # Now, create comparison images for each model
        comparison_images = []
        gt_pred_counts_metrics = []

        # Draw boxes for each model and store the images
        for model_name, pred_dir in models_dirs.items():
            print(f"Model: {model_name}")
            img_with_boxes, gt_count, pred_count, precision, recall = draw_boxes_and_calculate_metrics(img_name, model_name, pred_dir)
            comparison_images.append(img_with_boxes)
            gt_pred_counts_metrics.append((model_name, gt_count, pred_count, precision, recall))

        # Display the images with GT (red) and predictions (green) side by side
        display(*comparison_images)

        # Print GT and Pred counts, Precision and Recall for each model
        for model_name, gt_count, pred_count, precision, recall in gt_pred_counts_metrics:
            print(f"Model: {model_name} | GT: {gt_count} | Pred: {pred_count} | Precision: {precision:.3f} | Recall: {recall:.3f}")

# Run the comparison display
display_comparison_for_top_images()

